/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author Dares
 */
public class MenuInicio extends javax.swing.JFrame {
    
    Controlador elControlador = new Controlador();
   
    
    /**
     * Creates new form MenuInicio
     */
    public MenuInicio(){
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloBienvenido = new javax.swing.JLabel();
        BotonRegistro = new javax.swing.JButton();
        BotonMenuAdministrativo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloBienvenido.setFont(new java.awt.Font("Dialog", 1, 64)); // NOI18N
        TituloBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        TituloBienvenido.setText("Bienvenido");
        getContentPane().add(TituloBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 420, 142));

        BotonRegistro.setBackground(new java.awt.Color(255, 204, 0));
        BotonRegistro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonRegistro.setForeground(new java.awt.Color(0, 0, 0));
        BotonRegistro.setText("Registro");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 281, 313, 123));

        BotonMenuAdministrativo.setBackground(new java.awt.Color(255, 255, 255));
        BotonMenuAdministrativo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        BotonMenuAdministrativo.setForeground(new java.awt.Color(0, 0, 0));
        BotonMenuAdministrativo.setText("Administrativo");
        BotonMenuAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuAdministrativoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMenuAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 577, 212, 89));

        try {
            File pathToFile = new File("./imagenes/menuinicio.jpg");
            BufferedImage bufferImage = ImageIO.read(pathToFile);
            ImageIcon imageIcon = new ImageIcon(bufferImage);
            jLabel1.setIcon(imageIcon);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        Registro ventanaRegistro = new Registro(this,true,elControlador);
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void BotonMenuAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuAdministrativoActionPerformed
        IngresoAdministrador ingresoAdmi = new IngresoAdministrador(this,true,elControlador);
        ingresoAdmi.setVisible(true);
    }//GEN-LAST:event_BotonMenuAdministrativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenuAdministrativo;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JLabel TituloBienvenido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    
    
  
}
