/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dares
 */
public class ModificarTrabajador extends javax.swing.JDialog {

    private Controlador controlModificarTrabajador;
    
    public ModificarTrabajador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    ModificarTrabajador(ConfiguracionAdminitrador aThis, boolean modal, Controlador controlConfi) {
        super(aThis, modal);
        initComponents();
        controlModificarTrabajador = controlConfi;
    }
    private static boolean isInt(String cadena){
        try{
            Integer.parseInt(cadena);
            return true;
        }
        catch (NumberFormatException nfe){
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAtras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        buttonValidarCedula = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textCedulaNueva = new javax.swing.JTextField();
        textNombreNuevo1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        buttonModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAtras.setBackground(new java.awt.Color(255, 255, 0));
        buttonAtras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonAtras.setForeground(new java.awt.Color(0, 0, 0));
        buttonAtras.setText("Atras");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 31, 95, 33));

        jPanel1.setBackground(new java.awt.Color(255, 229, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Modificar Trabajador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel3)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 74, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 229, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel3.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre nuevo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 357, -1, -1));

        textCedula.setBackground(new java.awt.Color(241, 194, 50));
        textCedula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textCedula.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(textCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 211, 388, 38));

        buttonValidarCedula.setBackground(new java.awt.Color(255, 255, 0));
        buttonValidarCedula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonValidarCedula.setForeground(new java.awt.Color(0, 0, 0));
        buttonValidarCedula.setText("Validar Cedula");
        buttonValidarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidarCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonValidarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 280, 152, -1));

        jPanel4.setBackground(new java.awt.Color(255, 229, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cedula:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 211, -1, 38));

        textCedulaNueva.setBackground(new java.awt.Color(241, 194, 50));
        textCedulaNueva.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textCedulaNueva.setForeground(new java.awt.Color(0, 0, 0));
        textCedulaNueva.setEnabled(false);
        textCedulaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCedulaNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(textCedulaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 425, 388, 41));

        textNombreNuevo1.setBackground(new java.awt.Color(241, 194, 50));
        textNombreNuevo1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textNombreNuevo1.setForeground(new java.awt.Color(0, 0, 0));
        textNombreNuevo1.setEnabled(false);
        textNombreNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreNuevo1ActionPerformed(evt);
            }
        });
        getContentPane().add(textNombreNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 357, 388, 38));

        jPanel5.setBackground(new java.awt.Color(255, 229, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel5.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cedula nueva:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 425, 136, -1));

        buttonModificar.setBackground(new java.awt.Color(255, 255, 0));
        buttonModificar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonModificar.setForeground(new java.awt.Color(0, 0, 0));
        buttonModificar.setText("Modificar");
        buttonModificar.setEnabled(false);
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 510, 191, 71));

        try {
            File pathToFile = new File("./imagenes/admin.png");
            BufferedImage bufferImage = ImageIO.read(pathToFile);
            ImageIcon imageIcon = new ImageIcon(bufferImage);
            jLabel1.setIcon(imageIcon);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
       this.dispose();
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void buttonValidarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidarCedulaActionPerformed
        // TODO add your handling code here:
        if (isInt(textCedula.getText())){
            if(controlModificarTrabajador.validarCedulaControlador(Integer.parseInt(textCedula.getText()))){
                textNombreNuevo1.setEnabled(true);
                textCedulaNueva.setEnabled(true);
                buttonModificar.setEnabled(true);
                
            }else{
                JOptionPane.showMessageDialog(null,"ERROR.\nLa cedula no fue encontrada.");
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"ERROR.\nLa cedula debe ser un numero");
        }
    }//GEN-LAST:event_buttonValidarCedulaActionPerformed

    private void textCedulaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCedulaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCedulaNuevaActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        // TODO add your handling code here:
        if(controlModificarTrabajador.ModificarTrabajadorControlador(Integer.parseInt(textCedula.getText()), textNombreNuevo1.getText(), Integer.parseInt(textCedulaNueva.getText()))){
            JOptionPane.showMessageDialog(null,"Modificado exitosamente.");
        }else{
             JOptionPane.showMessageDialog(null,"ERROR.\nModificando...");
        }
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void textNombreNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreNuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreNuevo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarTrabajador dialog = new ModificarTrabajador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtras;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonValidarCedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textCedulaNueva;
    private javax.swing.JTextField textNombreNuevo1;
    // End of variables declaration//GEN-END:variables
}
