/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import Metodos.Carpintero;
import Metodos.Electricista;
import Metodos.OperadorDeMaquinaria;
import Metodos.Peon;
import Metodos.Soldador;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Dares
 */
public class RiesgosTrabajador extends javax.swing.JDialog {
        
    private Controlador controlRiesgosTrabajador;
    
     private String TituloPantalla = "                 Riesgos de un ";
     private String TituloOperadorMaquinaria = "     Riesgos de un ";
     private ArrayList RiesgosTrabajador = new ArrayList();
     private String Riesgo1;
     private String Riesgo2;
     private String Riesgo3;
     private String Riesgo4;
     private String Riesgo5;
     
    /**
     * Creates new form RiesgosTrabajador
     */
    public RiesgosTrabajador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public RiesgosTrabajador(ListaChequeos aThis, boolean modal, Controlador controlListaChequeo) {
        super(aThis,modal);
        initComponents();
        controlRiesgosTrabajador = controlListaChequeo;
        GenerandoRiesgos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TitutoRiesgos = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        TextoRiesgo1 = new javax.swing.JLabel();
        TextoRiesgo2 = new javax.swing.JLabel();
        TextoRiesgo3 = new javax.swing.JLabel();
        TextoRiesgo4 = new javax.swing.JLabel();
        TextoRiesgo5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 229, 153));
        jPanel1.setForeground(new java.awt.Color(255, 229, 153));

        TitutoRiesgos.setEditable(false);
        TitutoRiesgos.setBackground(new java.awt.Color(255, 229, 153));
        TitutoRiesgos.setBorder(null);
        TitutoRiesgos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(TitutoRiesgos);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        TextoRiesgo1.setBackground(new java.awt.Color(0, 0, 0));
        TextoRiesgo1.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        TextoRiesgo1.setForeground(new java.awt.Color(0, 0, 0));

        TextoRiesgo2.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N

        TextoRiesgo3.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N

        TextoRiesgo4.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N

        TextoRiesgo5.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TextoRiesgo1, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextoRiesgo2, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoRiesgo3, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoRiesgo4, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoRiesgo5, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoRiesgo1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoRiesgo2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoRiesgo3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoRiesgo4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TextoRiesgo5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 18, 1063, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 197, 66));

        try {
            File pathToFile = new File("./imagenes/listachequeo.jpg");
            BufferedImage bufferImage = ImageIO.read(pathToFile);
            ImageIcon imageIcon = new ImageIcon(bufferImage);
            jLabel2.setIcon(imageIcon);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1110, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiesgosTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiesgosTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiesgosTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiesgosTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RiesgosTrabajador dialog = new RiesgosTrabajador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoRiesgo1;
    private javax.swing.JLabel TextoRiesgo2;
    private javax.swing.JLabel TextoRiesgo3;
    private javax.swing.JLabel TextoRiesgo4;
    private javax.swing.JLabel TextoRiesgo5;
    private javax.swing.JTextPane TitutoRiesgos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
void GenerandoRiesgos(){
    
        RiesgosTrabajador.clear();
        String TrabajoTitulo = controlRiesgosTrabajador.ObtenerTrabajoActual();
        if(TrabajoTitulo == "Operador de Maquinaria"){
            TituloOperadorMaquinaria += TrabajoTitulo;
            TitutoRiesgos.setText(TituloOperadorMaquinaria);
        } else {
            TituloPantalla += TrabajoTitulo;
            TitutoRiesgos.setText(TituloPantalla);
        }
        
        if(TrabajoTitulo == "Carpintero"){
            Carpintero UnCarpintero = new Carpintero("temp",1, TrabajoTitulo);
            UnCarpintero.medidas_especificas();
            RiesgosTrabajador = UnCarpintero.getRiesgos_carpintero();

            Riesgo1 = (String) RiesgosTrabajador.get(0);
            Riesgo2 = (String) RiesgosTrabajador.get(1);
            Riesgo3 = (String) RiesgosTrabajador.get(2);
            Riesgo4 = (String) RiesgosTrabajador.get(3);
            Riesgo5 = (String) RiesgosTrabajador.get(4);
            
            TextoRiesgo1.setText(Riesgo1);
            TextoRiesgo2.setText(Riesgo2);
            TextoRiesgo3.setText(Riesgo3);
            TextoRiesgo4.setText(Riesgo4);
            TextoRiesgo5.setText(Riesgo5);
       }
       
        if(TrabajoTitulo == "Operador de Maquinaria"){
           
          OperadorDeMaquinaria UnOperadorDeMaquina = new OperadorDeMaquinaria("temp",1, TrabajoTitulo);
 
          UnOperadorDeMaquina.medidas_especificas();
          RiesgosTrabajador = UnOperadorDeMaquina.getRiesgos_operador_maquinaria();
          
          Riesgo1 = (String) RiesgosTrabajador.get(0);
          Riesgo2 = (String) RiesgosTrabajador.get(1);
          Riesgo3 = (String) RiesgosTrabajador.get(2);
          Riesgo4 = (String) RiesgosTrabajador.get(3);
          Riesgo5 = (String) RiesgosTrabajador.get(4);
            
          TextoRiesgo1.setText(Riesgo1);
          TextoRiesgo2.setText(Riesgo2);
          TextoRiesgo3.setText(Riesgo3);
          TextoRiesgo4.setText(Riesgo4);
          TextoRiesgo5.setText(Riesgo5);
       }
       
       if(TrabajoTitulo == "Peon"){
          
            Peon UnPeon = new Peon("temp",1, "Peon");
            UnPeon.medidas_especificas();
            RiesgosTrabajador = UnPeon.getRiesgos_peon();
            
            Riesgo1 = (String) RiesgosTrabajador.get(0);
            Riesgo2 = (String) RiesgosTrabajador.get(1);
            Riesgo3 = (String) RiesgosTrabajador.get(2);
            Riesgo4 = (String) RiesgosTrabajador.get(3);
            Riesgo5 = (String) RiesgosTrabajador.get(4);

            TextoRiesgo1.setText(Riesgo1);
            TextoRiesgo2.setText(Riesgo2);
            TextoRiesgo3.setText(Riesgo3);
            TextoRiesgo4.setText(Riesgo4);
            TextoRiesgo5.setText(Riesgo5);
       }
       
       if(TrabajoTitulo == "Electricista") {
           
            Electricista UnElectricista = new Electricista("temp",1, TrabajoTitulo);
            UnElectricista.medidas_especificas();
            RiesgosTrabajador = UnElectricista.getRiesgos_electricista();
            
            Riesgo1 = (String) RiesgosTrabajador.get(0);
            Riesgo2 = (String) RiesgosTrabajador.get(1);
            Riesgo3 = (String) RiesgosTrabajador.get(2);
            Riesgo4 = (String) RiesgosTrabajador.get(3);
            Riesgo5 = (String) RiesgosTrabajador.get(4);

            TextoRiesgo1.setText(Riesgo1);
            TextoRiesgo2.setText(Riesgo2);
            TextoRiesgo3.setText(Riesgo3);
            TextoRiesgo4.setText(Riesgo4);
            TextoRiesgo5.setText(Riesgo5);
        }
       
       if(TrabajoTitulo == "Soldador"){
        
        Soldador UnSoldador = new Soldador("temp",1, TrabajoTitulo);
       
        UnSoldador.medidas_especificas();
        RiesgosTrabajador = UnSoldador.getRiesgos_soldador();
        
        Riesgo1 = (String) RiesgosTrabajador.get(0);
        Riesgo2 = (String) RiesgosTrabajador.get(1);
        Riesgo3 = (String) RiesgosTrabajador.get(2);
        Riesgo4 = (String) RiesgosTrabajador.get(3);
        Riesgo5 = (String) RiesgosTrabajador.get(4);

        TextoRiesgo1.setText(Riesgo1);
        TextoRiesgo2.setText(Riesgo2);
        TextoRiesgo3.setText(Riesgo3);
        TextoRiesgo4.setText(Riesgo4);
        TextoRiesgo5.setText(Riesgo5);
        }
    }
}

