/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import Metodos.Carpintero;
import Metodos.Electricista;
import Metodos.OperadorDeMaquinaria;
import Metodos.Peon;
import Metodos.Soldador;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Dares
 */
public class TrabajosElegir extends javax.swing.JDialog {
    
    private Controlador controlTrabajosElegir;
    
    /**
     * Creates new form TrabajosElegir
     */
    public TrabajosElegir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public TrabajosElegir(Registro aThis, boolean modal, Controlador controlRegistro) {
        super(aThis,modal);
        initComponents();
        controlTrabajosElegir = controlRegistro;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonCarpintero = new javax.swing.JButton();
        BotonOperadorDMaquina = new javax.swing.JButton();
        BotonPeon = new javax.swing.JButton();
        BotonElectricista = new javax.swing.JButton();
        BotonSoldador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 229, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jPanel1.setForeground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione su Trabajo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 15, 530, 110));

        BotonCarpintero.setBackground(new java.awt.Color(255, 217, 102));
        BotonCarpintero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonCarpintero.setForeground(new java.awt.Color(0, 0, 0));
        BotonCarpintero.setText("Carpintero");
        BotonCarpintero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCarpinteroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCarpintero, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 320, 90));

        BotonOperadorDMaquina.setBackground(new java.awt.Color(255, 217, 102));
        BotonOperadorDMaquina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonOperadorDMaquina.setForeground(new java.awt.Color(0, 0, 0));
        BotonOperadorDMaquina.setText("Operador de maquinaria");
        BotonOperadorDMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOperadorDMaquinaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonOperadorDMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 320, 90));

        BotonPeon.setBackground(new java.awt.Color(255, 217, 102));
        BotonPeon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonPeon.setForeground(new java.awt.Color(0, 0, 0));
        BotonPeon.setText("Peón");
        BotonPeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPeonActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPeon, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 320, 90));

        BotonElectricista.setBackground(new java.awt.Color(255, 217, 102));
        BotonElectricista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonElectricista.setForeground(new java.awt.Color(0, 0, 0));
        BotonElectricista.setText("Electricista");
        BotonElectricista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElectricistaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonElectricista, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 320, 90));

        BotonSoldador.setBackground(new java.awt.Color(255, 217, 102));
        BotonSoldador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonSoldador.setForeground(new java.awt.Color(0, 0, 0));
        BotonSoldador.setText("Soldador");
        BotonSoldador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSoldadorActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSoldador, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 320, 90));

        try {
            File pathToFile = new File("./imagenes/elegir.jpg");
            BufferedImage bufferImage = ImageIO.read(pathToFile);
            ImageIcon imageIcon = new ImageIcon(bufferImage);
            jLabel2.setIcon(imageIcon);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCarpinteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCarpinteroActionPerformed
        
        boolean GuardandoTrabajoCarpintero = controlTrabajosElegir.GuardarTrabajo("Carpintero");
        this.dispose();
        ListaChequeos ventanaListaChequeo = new ListaChequeos(this,true,controlTrabajosElegir);
        ventanaListaChequeo.setVisible(true);
       
    }//GEN-LAST:event_BotonCarpinteroActionPerformed

    private void BotonOperadorDMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOperadorDMaquinaActionPerformed
        
        boolean GuardandoTrabajoOPM = controlTrabajosElegir.GuardarTrabajo("Operador de Maquinaria");
        this.dispose();
        ListaChequeos ventanaListaChequeo = new ListaChequeos(this,true,controlTrabajosElegir);
        ventanaListaChequeo.setVisible(true);
    }//GEN-LAST:event_BotonOperadorDMaquinaActionPerformed

    private void BotonPeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPeonActionPerformed
        
        boolean GuardandoTrabajoPeon = controlTrabajosElegir.GuardarTrabajo("Peon");
        this.dispose();
        ListaChequeos ventanaListaChequeo = new ListaChequeos(this,true,controlTrabajosElegir);
        ventanaListaChequeo.setVisible(true);
        
        
    }//GEN-LAST:event_BotonPeonActionPerformed

    private void BotonElectricistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElectricistaActionPerformed
        
        boolean GuardandoTrabajoElectricista = controlTrabajosElegir.GuardarTrabajo("Electricista");
        this.dispose();
        ListaChequeos ventanaListaChequeo = new ListaChequeos(this,true,controlTrabajosElegir);
        ventanaListaChequeo.setVisible(true);
        
    }//GEN-LAST:event_BotonElectricistaActionPerformed

    private void BotonSoldadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSoldadorActionPerformed
        
        boolean GuardandoTrabajoSoldador = controlTrabajosElegir.GuardarTrabajo("Soldador");
        this.dispose();
        ListaChequeos ventanaListaChequeo = new ListaChequeos(this,true,controlTrabajosElegir);
        ventanaListaChequeo.setVisible(true);
        
    }//GEN-LAST:event_BotonSoldadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrabajosElegir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrabajosElegir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrabajosElegir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabajosElegir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrabajosElegir dialog = new TrabajosElegir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCarpintero;
    private javax.swing.JButton BotonElectricista;
    private javax.swing.JButton BotonOperadorDMaquina;
    private javax.swing.JButton BotonPeon;
    private javax.swing.JButton BotonSoldador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
